" General settings
set nu
set ai
set tabstop=4
set shiftwidth=4
set expandtab
set ic
set incsearch
set cursorline
set showcmd
set hlsearch
set laststatus=2
set history=1000
set wildmode=longest,list,full
set wildignorecase
set termguicolors
set backspace=2
set background=dark
set completeopt-=preview
set foldmethod=indent
syntax on
language en_US.UTF-8
