" General settings
set nu
set ai
set si
set shiftwidth=2
set tabstop=2
set softtabstop=2
set expandtab
set ic
set incsearch
set cursorline
set showcmd
set hlsearch
set laststatus=2
set history=1000
set wildmode=longest,list,full
set wildignorecase
set termguicolors
set backspace=2
set background=dark
set completeopt=noinsert,menuone,noselect
set foldmethod=indent
syntax on
language en_US.UTF-8
